NOT_FOUND_ERROR = "The requested resource was not found."
INTERNAL_SERVER_ERROR = "An internal server error occurred."
INVALID_REQUEST = "Invalid request parameters."
UNAUTHORIZED = "Unauthorized access. Please authenticate."
PERMISSION_DENIED = "Permission denied for this operation."
ACTION_FAILED = "Action could not be completed."
DOCKER_DAEMON_UNAVAILABLE = "Docker daemon is unavailable or not running."
SERVICE_UNAVAILABLE = "Service is temporarily unavailable. Please try again later."

AUTH_SIGNUP_SUCCESS = "User registered successfully."
AUTH_SIGNUP_FAILURE = "User registration failed."
AUTH_USER_EXISTS = "Username already exists."
AUTH_LOGIN_SUCCESS = "Login successful."
AUTH_LOGIN_FAILURE = "Invalid username or password."
AUTH_TOKEN_CREATION_FAILURE = "Failed to create authentication token."
AUTH_TOKEN_EXPIRED = "Authentication token has expired."
AUTH_TOKEN_INVALID = "Invalid authentication token."
AUTH_REQUIRED = "Authentication is required to access this resource."
AUTH_FORBIDDEN = "You do not have permission to perform this action."
INVALID_CREDENTIALS = "Invalid username or password."

TOKEN_EXPIRED = "The token has expired. Please log in again."
INVALID_TOKEN = "Invalid or malformed token."

RATE_LIMIT_EXCEEDED = "Rate limit exceeded. Please try again later."
RATE_LIMIT_SUCCESS = "Rate limit for user successfully updated."
RATE_LIMIT_UPDATED = "User's rate limit successfully updated by admin."

IMAGE_BUILD_SUCCESS = "Docker image built successfully."
IMAGE_BUILD_FAILURE = "Failed to build Docker image."
IMAGE_PUSH_SUCCESS = "Docker image pushed successfully."
IMAGE_PUSH_FAILURE = "Failed to push Docker image to registry."
IMAGE_PULL_SUCCESS = "Docker image pulled successfully."
IMAGE_PULL_FAILURE = "Failed to pull Docker image from registry."
IMAGE_REMOVE_SUCCESS = "Docker image removed successfully."
IMAGE_REMOVE_FAILURE = "Failed to remove Docker image."
IMAGE_NOT_FOUND = "Requested image not found."
IMAGE_LIST_RETRIEVED = "List of Docker images retrieved successfully."
IMAGE_DELETE_SUCCESS = "Docker image deleted successfully."
IMAGE_LIST_SUCCESS = "Docker image listed successfully."

CONTAINER_CREATE_SUCCESS = "Docker container created successfully."
CONTAINER_CREATE_FAILURE = "Failed to create Docker container."
CONTAINER_STOP_SUCCESS = "Docker container stopped successfully."
CONTAINER_STOP_FAILURE = "Failed to stop Docker container."
CONTAINER_START_SUCCESS = "Docker container started successfully."
CONTAINER_START_FAILURE = "Failed to start Docker container."
CONTAINER_REMOVE_SUCCESS = "Docker container removed successfully."
CONTAINER_REMOVE_FAILURE = "Failed to remove Docker container."
CONTAINER_LOGS_RETRIEVED = "Docker container logs retrieved successfully."
CONTAINER_LOGS_FAILURE = "Failed to retrieve Docker container logs."
CONTAINER_LOGS_NOT_FOUND = "Requested container logs not found."
CONTAINER_LIST_FAILURE = "Failed to retrieve Docker containers."
CONTAINER_DETAILS_FAILURE = "Requested container not retrieved."
CONTAINER_NOT_FOUND = "Requested container not found."
CONTAINER_LIST_RETRIEVED = "List of Docker containers retrieved successfully."

VOLUME_CREATE_SUCCESS = "Docker volume created successfully."
VOLUME_CREATE_FAILURE = "Failed to create Docker volume."
VOLUME_REMOVE_SUCCESS = "Docker volume removed successfully."
VOLUME_REMOVE_FAILURE = "Failed to remove Docker volume."
VOLUME_NOT_FOUND = "Requested volume not found."
VOLUME_LIST_SUCCESS = "Requested volume retrieved successfully."
VOLUME_LIST_FAILURE = "Requested volume not retrieved."
VOLUME_LIST_RETRIEVED = "List of Docker volumes retrieved successfully."
VOLUME_RETRIEVE_FAILURE = "Volume retrieval failed."

STATUS_OK = "Request processed successfully."
STATUS_CREATED = "Resource created successfully."
STATUS_CONFLICT = "Request conflicts with existing data."
STATUS_INTERNAL_ERROR = "An unexpected error occurred. Please try again."

ADMIN_ACTION_SUCCESS = "Admin action successfully performed."
ADMIN_ACTION_FAILED = "Admin action could not be completed."

USER_CREATED_SUCCESS = "User created successfully."
USER_UPDATED_SUCCESS = "User updated successfully."
USER_DELETED_SUCCESS = "User deleted successfully."
USER_NOT_FOUND = "User not found."
USER_ACTION_FAILED = "User action failed."

USER_CONTAINERS_RETRIEVED = "User's containers retrieved successfully."
USER_CONTAINERS_ACCESS_DENIED = "You do not have permission to access other users' containers."
USER_MAX_CONTAINERS_REACHED = "User has reached the maximum number of containers allowed in this time window."

ADMIN_ACCESS_GRANTED = "Admin access granted."
USER_ACCESS_GRANTED = "User access granted."
ACCESS_DENIED = "Access denied. You do not have permission for this operation."

MONGODB_CONNECTION_FAILED = "Failed to connect to MongoDB."
